### ISSUE TITLE
Broken after switch to using private repo GitbookIO/syncgroup

### ISSUE THREAD

**Issue by blu3id** [GitbookIO/go-sqlpool#2]
Recent commit stripping utils/ in favour of GitbookIO/syncgroup has broken this package for other users (and users of upstream packages such as GitbookIO/micro-analytics) as this is a private repository. Please consider making it public.

**Comment by AaronO** [comment]
@blu3id Fixed by https://github.com/GitbookIO/syncgroup/issues/4
